#!/usr/bin/env python

"""
awftools
========

Daemon for the queueing system.
"""

from daemon import Daemon
from argparse import ArgumentParser

class AwfulDaemon(Daemon):
  """
  The main daemon class. Main loop is in run().
  Essentially copied from: 
    http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
  """

  def init_parser(self):
    parser = ArgumentParser(description="The awful-tools queuing daemon.")
    parse.add_argument( "-l", "--log", help="specify logfile")
    parse.add_argument( "-d", "--debug", 
                        help="output additional debugging information",
                        action="store_true"
                      )
    return parser.parse_args()

  def __init__(self, pidf, stdin='/dev/null', stdout='/dev/null', stderr='/dev/null'):
    args = init_parser()
    if args.log:
      of_log = open(args.log, 'w')
      stdout = of_log
    if args.log and args.debug:
      stderr = of_log
    super(AwfulDaemon, self).__init__(pidf, stdin, stdout, stderr)

  def parse_commands(self, string):
      



